## 1. numpy.array()

array() fonksiyonu, Python listelerini veya tuple'ları NumPy dizilerine (ndarray) dönüştürmek için kullanılır.

In [1]:
import numpy as np

# Normal bir Python listesi
liste = [1, 2, 3, 4, 5]

# NumPy dizisine çevirme
arr = np.array(liste)

print(arr)
print(type(arr))  # <class 'numpy.ndarray'>

[1 2 3 4 5]
<class 'numpy.ndarray'>


## 2. numpy.zeros()

Bu fonksiyon, belirli bir boyutta sıfırlardan oluşan bir NumPy dizisi oluşturur.

In [4]:
# 5x5 boyutunda sıfırlardan oluşan matris
zero_matrix = np.zeros((5, 5))

print(zero_matrix)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


## 3. numpy.ones()

Bu fonksiyon, belirli bir boyutta birlerden oluşan bir NumPy dizisi oluşturur.

In [6]:
# 2x4 boyutunda birlerden oluşan matris
ones_matrix = np.ones((2, 4))

print(ones_matrix)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## 4. numpy.arange()

Bu fonksiyon, belirli bir başlangıç, bitiş ve adım değeri ile bir dizi oluşturur.

In [8]:
# 0'dan 10'a kadar 2'şer artan dizi
arr = np.arange(0, 10, 2)

print(arr)  # [ 0  2  4  6  8]

[0 2 4 6 8]


## 5. numpy.linspace()

Belirtilen iki değer arasında eşit aralıklarla dizi oluşturur.

In [9]:
# 0 ile 1 arasında 5 eşit bölmeli dizi oluşturma
arr = np.linspace(0, 1, 5)

print(arr)  # [0.   0.25 0.5  0.75 1.  ]

[0.   0.25 0.5  0.75 1.  ]


## 6. numpy.reshape()

Bir NumPy dizisinin şeklini değiştirmek için kullanılır.

In [10]:
arr = np.arange(1, 10)  # [1 2 3 4 5 6 7 8 9]

# 3x3'lük matris haline getirme
reshaped_arr = arr.reshape((3, 3))

print(reshaped_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## 7. numpy.random.rand()

Bu fonksiyon, 0 ile 1 arasında rastgele değerler içeren bir dizi oluşturur.

In [11]:
# 3x3 boyutunda rastgele değerlerden oluşan matris
random_matrix = np.random.rand(3, 3)

print(random_matrix)

[[0.98269172 0.16507109 0.76022007]
 [0.64897028 0.53841531 0.5705594 ]
 [0.05147398 0.47322219 0.14244966]]


## 8. numpy.mean()

Bir dizinin elemanlarının ortalamasını hesaplar.

In [12]:
arr = np.array([10, 20, 30, 40, 50])

# Ortalama hesaplama
mean_value = np.mean(arr)

print(mean_value)  # 30.0

30.0


## 9. numpy.max() ve numpy.min() 

Bir dizinin en büyük (max) ve en küçük (min) değerlerini döndürür.

In [13]:
arr = np.array([15, 3, 7, 20, 11])

print("Maksimum:", np.max(arr))  # 20
print("Minimum:", np.min(arr))   # 3

Maksimum: 20
Minimum: 3


## 10. numpy.sum()

Bir dizideki tüm elemanların toplamını döndürür.

In [14]:
arr = np.array([1, 2, 3, 4, 5])

# Toplam hesaplama
sum_value = np.sum(arr)

print(sum_value)  # 15

15
